### PR TITLE
Adds tests for ARM template marshaling

### PR DESCRIPTION
**Pull request by m1kola**
cc @jim-minter

### CODE REVIEW

**Comment by jim-minter** [comment]
@m1kola I think this is over complex.  Can you just pick a real life representative case (say "marshal a NetworkSecurityGroup"), put some values in and check the resulting []byte?  Something like https://gist.github.com/jim-minter/efb19e8842cd69a26e49c437d65bbeaf ?

**Comment by m1kola** [comment]
@jim-minter I disagree here:

* Using types from Azure SDK hides some important details. Because the structure is defined in a separate package, it's not obvious that json tags should be taken into account during the marshaling process (if present), but custom marshaling logic defined in `MarshalJSON` should be dropped.
* At the same time types from the SDK add some unnecessary details\noise to the test: we have fields that cover tha same code path over and over again. And the value initialisation is quite long.
* It's hard to find a structure in the SDK that will provide the same level of test coverage that my fake structures provide (they cover almost all code paths except for some errors). We will have to use multiple types which will make the test even more poluted with unrelated things.
* Also I didn't want to add a dependency on Azure SDK to the test of the unit which doesn't really use it. 

I would prefer to keep it this way. To simplify the test we can drop cases without json tags, because we will likely not see these scenarios in real life. It will be something like: https://gist.github.com/m1kola/ae03590ba2bd3a793b5134ff28efba46

**Comment by jim-minter** [comment]
I 2/3 agree with you.  At the same time the test is hard to reason about and maintain.  I think you can reduce this to a single test with a single struct type with various sorts of fields appropriately initialised, checking against a known value.  Also, concentrate on testing what's newly implemented, not underlying Go functionality.

**Comment by jim-minter** [comment]
@m1kola bump

**Comment by m1kola** [comment]
Updated. Please take another look.

>  At the same time the test is hard to reason about and maintain.

I guess we will need to agree to disagree here :) I think, it's very subjective: I prefer to have smaller, more speicifc test cases in *unit tests*. in my opinion they are easier to read and update.

> I think you can reduce this to a single test with a single struct type with various sorts of fields appropriately initialised, checking against a known value.

I reduced it to a single structure, but I think it still makes sense to keep separate cases for zero and non-zero values to avoid duplicating fields of the same type.

>  Also, concentrate on testing what's newly implemented, not underlying Go functionality.

Custom marshaling is overriding standard Go behaviour here in a nonobvious way ([the bug with `[]byte` not marshaling into base64](https://github.com/jim-minter/rp/pull/6) is a good example), so I think it makes sense here to test:

* Structs with json tags and witohut json tags
* Structs with `MarshalJSON` and without it
* Basic types with zero and non-zero values

Hovever taking into account that we are going to use the `arm` package only with structs where we have both json tags and `MarshalJSON`, I'm happy to reduce a number of cases and add more later if we need to.

**Comment by jim-minter** [comment]
merged, thanks

**Pull request closed without merging**
